apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: odoo-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres
        env:
        - name: POSTGRES_USER
          value: "odoo"
        - name: POSTGRES_PASSWORD
          value: "odoo"
        - name: POSTGRES_DB
          value: "postgres"
        ports:
        - containerPort: 5432
